# Generated by Django 4.1.6 on 2023-05-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_end_date_project_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
