# Generated by Django 4.1.6 on 2023-05-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_iteration_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteration',
            name='name',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
