version: "3.10"
services:
  db:
    image: postgres
    ports:
     - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env

  web:
    build: .
    tty: true
    command:  bash -c 'python manage.py collectstatic --no-input &&
              python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    build: ./nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/staticfiles

    depends_on:
      - web
volumes:
  static:

